version: "1.1"

on:
  push:
    branches:
      - master
      - release/*
    tags:
      - v*

stages:
  - stage:
      - git-checkout:
          alias: erda-operator
          params:
            depth: 1
  - stage:
      - extract-repo-version:
          params:
            git_dir: ${{ dirs.erda-operator }}
  - stage:
      - dockerfile:
          alias: dockerfile
          version: "1.0"
          params:
            build_args:
              GO_PROJECT_ROOT: "github.com/erda-project/erda"
              GO_PROXY: "https://goproxy.cn,direct"
            image:
              name: erda-operator
              tag: ${{ outputs.extract-repo-version.image_tag }}
            path: ${{ dirs.erda-operator }}/Dockerfile
            registry:
              password: ${{ configs.docker_registry_password }}
              url: ${{ configs.docker_registry }}
              username: ${{ configs.docker_registry_username }}
            workdir: ${{ dirs.erda-operator }}
  - stage:
      - release:
          alias: release-ui
          description: 用于打包完成时，向dicehub 提交完整可部署的dice.yml。用户若没在pipeline.yml里定义该action，CI会自动在pipeline.yml里插入该action
          version: "1.0"
          params:
            image:
              erda-operator: ${{ outputs.dockerfile.image }}
            tag_version: ${{ outputs.extract-repo-version.version }}