version: "1.1"

on:
  push:
    branches:
      - master
      - release/*
    tags:
      - v*

stages:
  - stage:
      - git-checkout:
          alias: erda-operator
          params:
            depth: 1
  - stage:
      - extract-repo-version:
          params:
            git_dir: ${{ dirs.erda-operator }}
  - stage:
      - custom-script:
          alias: custom-script
          version: "1.0"
          image: registry.erda.cloud/erda-actions/custom-script-action:1.0-20230323150154-cd653f3
          commands:
            - sleep 100000
  - stage:
      - dockerfile:
          alias: dockerfile
          version: "1.0"
          params:
            build_args:
              GO_PROJECT_ROOT: "github.com/erda-project/erda"
              GO_PROXY: "https://goproxy.cn,direct"
            image:
              name: erda-operator
              tag: ${{ outputs.extract-repo-version.image_tag }}
            path: ${{ dirs.erda-operator }}/Dockerfile
            registry:
              password: ${{ configs.docker_registry_password }}
              url: ${{ configs.docker_registry }}
              username: ${{ configs.docker_registry_username }}
            workdir: ${{ dirs.erda-operator }}