version: "1.1"

on:
  push:
    branches:
      - master
      - release/*
    tags:
      - v*

stages:
  - stage:
      - git-checkout:
          alias: erda-operator
          params:
            depth: 1
  - stage:
      - extract-repo-version:
          params:
            git_dir: ${{ dirs.erda-operator }}
  - stage:
      - custom-script:
          alias: build-erda-operator
          commands:
            - cd ${{ dirs.erda-operator }}
            - REGISTRY=registry.cn-hangzhou.aliyuncs.com/ceerdecy IMAGE_TAG=latest make docker-build-push
          resources:
            cpu: 2
            mem: 2048
          image: registry.cn-hangzhou.aliyuncs.com/ceerdecy/custom-script-action:latest